# Generated by Django 3.1.7 on 2023-01-06 08:16

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='нэр')),
                ('description', models.CharField(max_length=250, verbose_name='тайлбар')),
                ('icon', models.FileField(null=True, upload_to='', verbose_name='зураг')),
                ('order', models.IntegerField(verbose_name='дараалал')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='гарчиг')),
                ('picture', models.FileField(null=True, upload_to='')),
                ('content', models.TextField()),
                ('creation_date', models.DateTimeField(default=datetime.datetime.now)),
                ('publish_date', models.DateTimeField(default=datetime.datetime.now)),
                ('view', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='хэрэглэгч')),
            ],
        ),
    ]
