# Generated by Django 3.1.7 on 2023-01-06 08:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20230106_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category', verbose_name='категори'),
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(verbose_name='дэлгэрэнгүй'),
        ),
        migrations.AlterField(
            model_name='new',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Үүсгэсэн огноо'),
        ),
        migrations.AlterField(
            model_name='new',
            name='picture',
            field=models.FileField(null=True, upload_to='', verbose_name='зураг'),
        ),
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Нийтэлсэн огноо'),
        ),
        migrations.AlterField(
            model_name='new',
            name='view',
            field=models.IntegerField(verbose_name='Үзсэн тоо'),
        ),
    ]
